# -*- mode:yaml; indent-tabs-mode: nil; -*-
---

name: build-and-test
on:
  workflow_call:
    # No attempt to enforce strong data types.
    inputs:
      php-version:
        description: 'The php version under which to test'
        type: string
        default: '8.1'
      compiler-optimization-level:
        description: 'setting of the -O flag'
        type: string
        default: '2'
      valgrind-tool:
        description: 'tool to pass to -M e.g. memcheck'
        type: string
        default: 'none'
jobs:
  build-and-test-job:
    name: Test in PHP version ${{ inputs.php-version }}
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: |
          lsb_release -a
          sudo apt-get update
          sudo apt install valgrind
      - name: Check basic dependencies
        run: |
          valgrind --version
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: install sqlrelay vendor dependencies
        run: |
          bash bin/sqlrelay-vendor-pkgs.sh show-env
          bash bin/sqlrelay-vendor-pkgs.sh download
          bash bin/sqlrelay-vendor-pkgs.sh apt-enable
          bash bin/sqlrelay-vendor-pkgs.sh apt-install
      - name: Setup PHP
        uses: "shivammathur/setup-php@v2"
        with:
          php-version: "${{ inputs.php-version }}"
          coverage: "none"
          tools: "phpize, php-config"
      - name: Generate build files
        run: phpize
      - name: Configure build
        # Note: When passed to make use CXXFLAGS, but configure looks at CFLAGS
        run: >-
          CFLAGS="-g -Wall -fstack-protector-strong -O${{ inputs.compiler-optimization-level}}"
          ./configure
      - name: Build
        run: make all
      - name: PHP Info
        run: php -info
      - name: setup log dirs
        run: >-
          mkdir artifacts artifacts/client-log artifacts/test
          artifacts/exe artifacts/build artifacts/server-log
      - name: collect package info
        run: |
         lsb_release -a > artifacts/build/environment.txt
         echo "" >> artifacts/build/environment.txt
         php --version >> artifacts/build/environment.txt
         apt list --installed "sqlrelay*" "rudiments*" > artifacts/build/installed.txt
      - name: start Microsoft SQL Server
        run: bash bin/mssql.sh start
      - name: sleep before testing mssql
        # We could do a loop until the test succeeds
        run: sleep 15
      - name: test mssql
        run: bash bin/mssql.sh test
      - name: setup mssql
        run: bash bin/mssql.sh setup
      - name: config sqlrelay
        run: bash bin/sqlrelay.sh config
      - name: start sqlrelay
        run: bash bin/sqlrelay.sh start
      - name: test sqlrelay
        run: bash bin/sqlrelay.sh test
      - name: Run tests
        run: >-
          SQLR_CLIENT_DEBUG_PREFIX=artifacts/client-log/
          RUN_FAILING_TESTS=1
          REPORT_EXIT_STATUS=1
          NO_INTERACTION=1
          TEST_PHP_EXECUTABLE=$(which php)
          php -n
          -d open_basedir=
          -d output_buffering=0
          -d memory_limit=-1
          run-tests.php -n
          ${{ inputs.valgrind-tool != 'none' && format('-M {0}', inputs.valgrind-tool) || '' }}
          -d extension_dir=modules
          -d extension=$(php -r 'echo PHP_EXTENSION_DIR;')/pdo.so
          -d extension=pdo_sqlrelay.so
          tests
      - name: stop sqlrelay
        if: always()
        run: bash bin/sqlrelay.sh stop
      - name: stop Microsoft SQL Server
        if: always()
        run: bash bin/mssql.sh stop
      - name: collect artifacts
        if: always()
        run: |
         bash bin/careful-mv.sh tests/*.diff tests/*.mem artifacts/test
         bash bin/careful-mv.sh modules/pdo_sqlrelay.so artifacts/exe
         bash bin/careful-mv.sh /var/log/sqlrelay/debug/* /var/log/sqlrelay/odbc/* artifacts/server-log
      - name: publish artifacts
        if: always()
        uses: actions/upload-artifact@v3
        with: 
          name: artifacts-of-test-${{ inputs.php-version }}
          path: artifacts
