# -*- mode:yaml; indent-tabs-mode: nil; -*-

name: dispatch-build-and-test

on:
  workflow_dispatch:
    # Strongly type these inputs to reduce operator error
    inputs:
      php-version:
        description: 'The PHP version '
        required: true
        default: '8.1'
        type: choice
        options:
          - '7.4'
          - '8.0'
          - '8.1
      compiler-optimization-level:
        description: 'Setting of the gcc -O flag'
        default: '2'
        type: choice
        options:
          - '2'
          - '1'
          - '0'
      valgrind-tool:
        description: 'What valgrind tool to use'
        default: ''
        type: choice
        options:
          - ''
          - 'memcheck'
jobs:
  call-build-and-test:
    uses: ./.github/workflows/build-and-test.yml
    with:
      php-version: ${{ inputs.php-version }}
      compiler-optimization-evel: ${{ inputs.compiler-optimization-level }}
      valgrind-tool: ${{ inputs.compiler-optimization-level }}
