# -*- mode:yaml; indent-tabs-mode: nil; -*-

# It is useful to strongly type inputs to a workflow_dispatch,
# giving specific options whenever possible, to minimize
# operator errors. This first cut, no inputs at all.


---

name: 'dispatch-build-and-test'

on:
  workflow_dispatch:
    inputs:
      phpversion:
        description: 'what php version to test against'
        required: true
        default: '8.1'
      compileroptimizationlevel:
        description: 'The -O flag number'
        required: true
        default: '2'
      valgrindtool:
        description: 'If not blank, the -M valgrind too argument, e.g. memcheck'
        required: false
        default: ''

jobs:
  call-build-and-test:
    uses: ./.github/workflows/build-and-test.yml
    with:
      php-version: ${{ inputs.phpversion }}
      compiler-optimization-level: ${{ inputs.compileroptimizationlevel }}
      valgrind-tool: ${{ inputs.valgrindtool }}
