# -*- mode:yaml; indent-tabs-mode: nil; -*-

# It is useful to strongly type inputs to a workflow_dispatch,
# giving specific options whenever possible, to minimize
# operator errors.

---

name: dispatch-build-and-test

on:
  workflow_dispatch:

jobs:
  call-build-and-test:
    uses: ./.github/workflows/build-and-test.yml
    with:
      php-version: ${{ inputs.php_version }}
      compiler-optimization-evel: ${{ inputs.compiler_optimization_level }}
      valgrind-tool: ${{ inputs.valgrind_tool }}
