# -*- mode:yaml; indent-tabs-mode: nil; -*-

# It is useful to strongly type inputs to a workflow_dispatch,
# giving specific options whenever possible, to minimize
# operator errors. This first cut, no inputs at all.


---

name: dispatch-build-and-test

on:
  workflow_dispatch:
    inputs:
      php_version:
        required: true
        description: 'The PHP version '
        default: '8.1'
        type: choice
        options:
        - '7.4'
        - '8.0'
        - '8.1
      compiler_optimization_level:
        required: true
        description: 'Setting of the gcc -O flag'
        default: '2'
        type: choice
        options:
        - '2'
        - '1'
        - '0'
      valgrind_tool:
        required: true
        description: 'What valgrind tool to use'
        default: ''
        type: choice
        options:
        - ''
        - 'memcheck'

jobs:
  call-build-and-test:
    uses: ./.github/workflows/build-and-test.yml
    with:
      php-version: '8.1'
      compiler-optimization-level: 2
      valgrind-tool: 'memcheck'
